# Site settings

title: Avian Health Biology - The University of Delaware
author: Yitbarek
logo: ![UD logo](https://github.com/ayitbarek/AHB-Lab/blob/af76eb398899e31678727ba876471f1a3b5d23be/Images/Logo.png)

# Build settings
markdown: kramdown
theme: minima
