# basic options
title: AHB-Lab\nAvian Health Biology - The University of Delaware
author:

description: >
  This is the first line.\n
  This is the second line.\n
  This is the third line.


# Build settings
markdown: kramdown
theme: minima
